version: '3.3'
services:
  posetgres:
    container_name: ${POSTGRES_CONTAINER_NAME}
    image: postgres:14.1-alpine
    restart: always
    networks:
      - project
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: postgres_db
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./${POSTGRES_MOUNT_PATH}:/var/lib/postgresql/data

volumes:
  postgres:
    driver: local
 

networks:
  project: