APP:
  NAME: server
  STAGE: LOCAL
  VERSION: 0.0.1

HTTP:
  PORT: 8888
  HOST: 0.0.0.0

SWAGGER:
  URL: 'localhost:8888'

LOG:
  PATH_LOGGER: logs


POSTGRES_DB:
  HOST: localhost
  PORT: 54328
  NAME: postgres_db
  USER: admin
  PASS: admin
  SCHEMA: public
  MAX_IDLE_CONNS: 10
  MAX_OPEN_CONNS: 40
  TX_RETRY_COUNT: 1
  CONN_MAX_LIFE_TIME: 5
  DIR_MIGRATION: "../../internal/user/migrations"

JWT:
  ACCESS_SECRET_KEY: "Y293c3BpbmNvbmRpdGlvbm1vdmllc21vb3RodHdlbHZldGhlcmVmb3Jlb3JhbmdlY28=" # random generate
  ACCESS_TOKEN_EXPIRE_TIME: 3600000 # 1000 hours

MINIO:
  PUBLIC_ENDPOINT: "http://localhost:9000"
  SERVER_ENDPOINT: "localhost:9000"
  ACCESS_KEY: "G222qn4yr10CLhdPUzEX"
  SECRET_KEY: "0BP5SqbZkKaUazVRs0HfO8a9N2nNV2MOFHom6fzq"
  USE_SSL: false
